### ISSUE TITLE
Cities photo on home page

### ISSUE THREAD

**Issue by eugenern** [cs373gc-fall-2016/Startup-Fairy#103]
Broken for me, anyway.
![screenshot_20161117-135556](https://cloud.githubusercontent.com/assets/8752461/20405371/5a925546-acce-11e6-9aef-0fdb88a0ad57.png)

**Comment by addykim** [comment]
Launched startupfairy on my phone and via dev console's mobile setting. I do not see this issue.

**Comment by eugenern** [comment]
Fixed by ajmal in d23396856e8edb5ed494ab9a958bdeb7062a6b02
