### ISSUE TITLE
Setup travis.yml

### ISSUE THREAD

**Issue by addykim** [cs373gc-fall-2016/Startup-Fairy#19]
Repository has been imported into Travis-ci, but .travis.yml is empty. Fill out .travis.yml.

Please also disable email notifications.
Link to travis:  https://travis-ci.org/cs373gc-fall-2016/TBD

**Comment by addykim** [comment]
Disabled email notifications for travis. We will not be using continuous integrations for phase1.

**Comment by addykim** [comment]
Travis just ran its first working build (doesn't do much)

**Comment by marktheperson** [comment]
@summergirl21 is this done? can we close this?
