### ISSUE TITLE
Each member leaves their member info here

### ISSUE THREAD

**Issue by addykim** [cs373gc-fall-2016/Startup-Fairy#3]
for each member:
name
photo
bio

**Comment by addykim** [comment]
Addy Kim
Link to image: [http://addy.tech/assets/avatar.jpg](http://addy.tech/assets/avatar.jpg)
bio: I'm a cat loving Computer Science major at the University of Texas. In my free time I enjoy doing wushu and crafts.

**Comment by marktheperson** [comment]
![avatar](https://cloud.githubusercontent.com/assets/6691919/19447404/fd4cc782-9462-11e6-883c-76415da2127c.jpg)
Marcus Cruz
link to image: [click me](https://marktheperson.github.io/)
Bio: Hey y’all, my name is Marcus Cruz, but I also go by Mark. I’m a student at the University of Texas at Austin studying computer science. My hobbies are photography, video games, hiking, and listening to music.

**Comment by ilinum** [comment]
Svyatoslav Ilinskiy
Picture: [click here](https://github.com/ilinum.png)
Bio: Hi, my name is Svyatoslav but I go by Stas. I study CS at UT Austin. previously, I have interned at JetBrains, working on Scala plugin for IntelliJ. I like hiking and having fun

**Comment by summergirl21** [comment]
Madeline Stager
Picture: [here](https://raw.githubusercontent.com/summergirl21/swe-blog/master/images/Headshot.jpg)
Bio: Hi, I'm a Computer Science student at UT Austin. In my free time I like hiking, camping and playing frisbee.

**Comment by cameronreynoldson** [comment]
Cameron Reynoldson
Picture: <a href="https://avatars0.githubusercontent.com/u/8815436?v=3&s=460"> here </a>
Bio: I love all things fat cats, competitive programming and infrastructure. I'm currently a CS major at UT Austin and worked at Dropbox this past summer on rebuilding their feature gating system in Go.

**Comment by ajrator** [comment]
Ajmal Khan
Picture: [Here](https://avatars.githubusercontent.com/ajrator)
Bio: I am currently studying Computer Science at The University of Texas at Austin and have interned with Dell and MD Anderson. I love fiddling with Python and playing the guitar.

**Comment by eugenern** [comment]
Eugene Ng
Picture: [here](https://avatars.githubusercontent.com/eugenern)
Bio: I'm a student in Computer Science at UT Austin. In my free time I enjoy following the NBA and occasionally listening to music or playing video games.
