### ISSUE TITLE
Create technical report using GitHub Wiki

### ISSUE THREAD

**Issue by marktheperson** [cs373gc-fall-2016/Startup-Fairy#4]
Requirements:

Section
- Feature

Title   
- The group name.
- The group members.

Introduction  
What is the problem?
What are the use cases?

Design  
- RESTful API

Tools   
- front-end
- back-end
- embedding-media services

Hosting 
- How do you set up the Digital Ocean or AWS server?

Other   
- Proof-read your report. Get another group to read it. Read it aloud.

Create diagrams with captions.
Create sections and subsections effectively.

**Comment by addykim** [comment]
Closing in favor of using smaller issues per section
