### ISSUE TITLE
Make changes to splash page

### ISSUE THREAD

**Issue by addykim** [cs373gc-fall-2016/Startup-Fairy#40]
Add more content? Change the links? Do the nav buttons match the links on the splash page
Close if there is no changes need to be made

**Comment by summergirl21** [comment]
Changed nav buttons https://github.com/cs373gc-fall-2016/Startup-Fairy/commit/c35c71d9bdd536938fc64f1e7ed81a6f748f36be
Should any other changes be made?

**Comment by summergirl21** [comment]
Maybe look for better pictures? Especially for organizations and maybe companies?

**Comment by addykim** [comment]
Go for it.
