### ISSUE TITLE
Increase number of attributes to display

### ISSUE THREAD

**Issue by addykim** [cs373gc-fall-2016/Startup-Fairy#51]
We're not displaying enough attributes in the tables.

Relevant piazza https://piazza.com/class/iryccp26g9wou?cid=245

**Comment by ilinum** [comment]
So it's hard to get more info from the crunchbase database. 

I think it's not ideal but fine to display people's twitter usernames.

**Comment by addykim** [comment]
Per discussed in person we'll just go ahead and do that

**Comment by addykim** [comment]
Once models is complete, then we will change `category.html` to display more attributes.
