### ISSUE TITLE
Create a visualization page

### ISSUE THREAD

**Issue by ajrator** [cs373gc-fall-2016/Startup-Fairy#80]
Should exercise the use of another group's REST API

**Comment by marktheperson** [comment]
Group: IDB 5
Group Name: Southern Wholesome Education(SWE)
Group URL: wholesomeeducation.me

"Use D3.js
The page must have a clear English description and be rendered attractively."

**Comment by addykim** [comment]
Moved `team_five.html` to `startupfairy/templates`. Also added a route so you can find this html file at `/education`, but did not add to the navigation
