### ISSUE TITLE
Create a critique of another group's website by answering the following questions

### ISSUE THREAD

**Issue by ajrator** [cs373gc-fall-2016/Startup-Fairy#81]
What did they do well?
What did we learn from their website?
What can they do better?
What puzzles us about their website?
Group critique order will be from the URLs posted on Piazza @231:
Group 1 critiques Group 2.
Group 2 critiques Group 3.
...
Group N critiques Group 1.

**Comment by marktheperson** [comment]
Group: IDB 5
Group Name: Southern Wholesome Education(SWE)
Group URL: wholesomeeducation.me
