### ISSUE TITLE
Implement search capability

### ISSUE THREAD

**Issue by ajrator** [cs373gc-fall-2016/Startup-Fairy#83]
The search must search every attribute of every model
The result of a search must be a list of links to crises and/or organizations and/or people (e.g. like Google).
The results must be contextualized and the search terms must show up and be highlighted.
The results must be clickable.
The results must be dense with at least 10 results per page.
The results must be paginated if there are more than 10 results.
Multi-word search must show clearly marked and results followed by or results.

**Comment by cameronreynoldson** [comment]
This has been completed on the back-end side.
