### ISSUE TITLE
Tests can't run on about page

### ISSUE THREAD

**Issue by addykim** [cs373gc-fall-2016/Startup-Fairy#87]
<img width="1213" alt="screen shot 2016-11-08 at 6 18 28 pm" src="https://cloud.githubusercontent.com/assets/7654513/20122760/d208f1ac-a5df-11e6-94b0-d0a2949438da.png">

**Comment by marktheperson** [comment]
fixed in 74ea5894ac1db2c617b7c33b6e4051d9c4efe5c8
